upstream webserv_upstream {
    server webserv:8080; 
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name localhost aelsayed.42.fr;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/wordpress;
    index index.php index.wordpress;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    location /adminer {
        proxy_pass http://adminer:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /webserv {
        return 301 /webserv/;
    }

    location /webserv/ {
        proxy_pass http://webserv_upstream/;
        proxy_set_header Host webserv:8080;
        proxy_redirect ~^(/.*)$ /webserv$1;
    }

    location ~ ^/(desc|login|tests|uploads|cgi-bin)(/.*)?$ {
        proxy_pass http://webserv_upstream;
        proxy_set_header Host webserv:8080;
    }
}
