services:
  # Mandatory
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes: [nginx_data:/var/www/wordpress]
    ports: ["443:443"]
    depends_on: [wordpress]
    restart: always
    networks: [inception]
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes: [mariadb_data:/var/lib/mysql]
    env_file: [.env]
    restart: always
    networks: [inception]
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes: [nginx_data:/var/www/wordpress]
    ports: ["9000:9000"]
    depends_on: [mariadb]
    env_file: [.env]
    restart: always
    networks: [inception]
  # Bonus
  adminer:
    build: ./bonus/adminer
    container_name: adminer
    restart: unless-stopped
    networks: [inception]
    depends_on: [mariadb]
  redis:
    build: ./bonus/redis
    container_name: redis
    restart: unless-stopped
    networks: [inception]
    depends_on: [wordpress]
  webserv:
    build: ./bonus/webserv
    container_name: webserv
    volumes: ['webserv:/webserv']
    restart: unless-stopped
    networks: [inception]
  ftp:
    container_name: ftp
    build: ./bonus/ftp
    restart: always
    env_file: [.env]
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    ports: ["21:21", "40000-40005:40000-40005"]
    volumes: [nginx_data:/var/www/wordpress]
    networks: [inception]
    depends_on: [wordpress]
  playground:
    build: ./bonus/playground
    container_name: playground
    restart: unless-stopped
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    networks: [inception]


networks:
  inception:
    driver: bridge

volumes:
  nginx_data:
    name: nginx_volume
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/nginx
      o: bind
  mariadb_data:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind
  webserv:
    name: webserv_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/$USER/data/webserv'
