[www]
user = www-data
group = www-data

; Use 9000 to listen to the whole network
listen = 9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Crucial: This allows PHP to read the environment variables (passwords)
clear_env = no